name: xdn_web_app
description: XDN Web APP

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^6.0.1
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  rxdart: ^0.27.7
  flutter_secure_storage: ^7.0.1
  http: ^0.13.5
  grpc: ^3.1.0
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
