#!/bin/bash

/bin/bash ./compile.sh
sftp -i ~/.ssh/xdn XDNService@194.60.201.213:/home/XDNService/apiVoting/ <<< $'put api apiu'
ssh -i ~/.ssh/xdn XDNService@194.60.201.213 "/home/XDNService/apiVoting/update"