name: digitalnote
description: DigitalNote App Wallet

publish_to: 'none'

version: 1.1.57+138

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^16.3.2
  firebase_messaging: any
  firebase_core: any
  google_fonts: ^6.1.0
  qr_flutter: ^4.1.0
  sqflite: ^2.3.2
  sprintf: ^7.0.0
  get_it: ^7.6.7
  auto_size_text: ^3.0.0
  share_plus: ^7.2.2
  vibration: ^1.8.4
  flutter_udid: ^3.0.0
  url_launcher: ^6.2.5
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_native_image:
    git:
      url: https://github.com/MagTuxGit/flutter_native_image
      ref: master
  flutter_phoenix: ^1.1.1
  flutter_app_badger: ^1.5.0
  bubble: ^1.2.1
  flutter_typeahead:
    git:
      url: https://github.com/M1chlCZ/flutter_typeahead.git
      ref: master
  flutter_linkify: ^6.0.0
  vector_math: ^2.1.4
  font_awesome_flutter: ^10.7.0
  flutter_countdown_timer: ^4.1.0
  shared_preferences: ^2.2.2
  badges: ^3.1.2
  crypto: any
  mobile_scanner: ^4.0.0
  fl_chart: ^0.66.2
  jiffy: ^6.2.1
  permission_handler: ^11.3.0
  local_auth: ^2.2.0
  walletconnect_qrcode_modal_dart: ^0.4.3
  web3dart: ^2.7.1
  decimal: ^2.3.3
  rxdart: ^0.27.7
  open_filex: ^4.4.0
  external_path: ^1.0.3
  path: ^1.9.0
  avatar_glow: ^3.0.1
  styled_text: ^8.1.0
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  slide_to_act: any
  flutter_native_splash: ^2.3.10
  screenshot: ^2.1.0
  flutter_riverpod: ^2.4.10
  grpc: ^3.2.4
  model_viewer_plus: ^1.7.0
  flutter_biometrics:
    git:
      url: https://github.com/M1chlCZ/flutter_biometrics.git
      ref: main
  walletconnect_dart: any
  protobuf: any
  cupertino_icons: ^1.0.6

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
