name: digitalnote
description: DigitalNote App Wallet

publish_to: 'none'

version: 1.1.46+129

environment:
  sdk: ">=2.18.0 <3.3.9"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.2.5
  firebase_core: ^2.7.0
  google_fonts: ^4.0.3
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  sqflite: ^2.2.4+1
  sprintf: ^7.0.0
  get_it: ^7.2.0
  auto_size_text: ^3.0.0
  share_plus: ^6.3.1
  vibration: ^1.7.6
  flutter_udid: ^2.0.1
  url_launcher: ^6.1.10
  image_cropper: ^3.0.1
  image_picker: ^0.8.6+3
  path_provider: ^2.0.13
  flutter_native_image: ^0.0.6+1
  flutter_phoenix: ^1.1.0
  flutter_app_badger: ^1.5.0
  bubble: ^1.2.1
  flutter_typeahead:
    git:
      url: https://github.com/M1chlCZ/flutter_typeahead.git
      ref: master
  flutter_linkify: ^5.0.2
  vector_math: ^2.1.4
  font_awesome_flutter: ^10.4.0
  flutter_countdown_timer: ^4.1.0
  shared_preferences: ^2.0.18
  badges: ^3.0.2
  crypto: any
  mobile_scanner: ^2.1.0
  fl_chart: ^0.61.0
  jiffy: ^5.0.0
  permission_handler: ^10.2.0
  local_auth: ^2.1.5
  walletconnect_qrcode_modal_dart: ^0.3.0
  web3dart: ^2.6.1
  decimal: ^2.3.2
  rxdart: ^0.27.7
  open_filex: 4.3.2
  external_path: ^1.0.3
  path: ^1.8.2
  avatar_glow: ^2.0.2
  styled_text: ^7.0.0
  package_info_plus: ^3.0.3
  device_info_plus: ^8.1.0
  flutter_displaymode: ^0.5.0
  slide_to_act: ^2.0.1
  flutter_native_splash: ^2.2.18
  screenshot: ^1.3.0
  flutter_riverpod: ^2.2.0
  grpc: ^3.1.0
  model_viewer_plus: ^1.5.0
  flutter_biometrics:
    git:
      url: https://github.com/M1chlCZ/flutter_biometrics.git
      ref: main
#dependency_overrides:
#  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
          weight: 200

