name: digitalnote
description: DigitalNote App Wallet

publish_to: 'none'

version: 1.0.62+62

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  flutter_secure_storage: ^6.0.0
  flutter_local_notifications: ^12.0.3
  firebase_messaging: any
  firebase_core: any
  package_info: any
  google_fonts: any
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  sqflite: ^2.2.0+2
  tuple: ^2.0.1
  encrypt: ^5.0.1
  sprintf: any
  get_it: ^7.2.0
  auto_size_text: ^3.0.0
  share: any
  vibration: ^1.7.6
  flutter_udid: ^2.0.0
  url_launcher: ^6.1.6
  image_cropper: ^3.0.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  flutter_native_image: ^0.0.6+1
  flutter_phoenix: ^1.1.0
  flutter_app_badger: ^1.5.0
  bubble: ^1.2.1
  flutter_typeahead: ^4.1.1
  flutter_linkify: ^5.0.2
  vector_math: ^2.1.2
  font_awesome_flutter: ^10.2.1
  flutter_native_timezone: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  badges: ^2.0.3
  crypto: any
  mobile_scanner: ^2.0.0
  fl_chart: ^0.55.2
  jiffy: ^5.0.0
  permission_handler: ^10.2.0
  local_auth: ^2.1.2
  walletconnect_qrcode_modal_dart: ^0.0.6
  web3dart: ^2.4.1
  decimal: any
  jwt_decode: ^0.3.1
  rxdart: ^0.27.5
  open_file: ^3.2.1
  external_path: ^1.0.3
  path: any
  avatar_glow: any
  styled_text: any
  flutter_displaymode: ^0.4.0
  slide_to_act: any
  flutter_native_splash: ^2.2.12
  flutter_biometrics:
    git:
      url: https://github.com/M1chlCZ/flutter_biometrics.git
      ref: main

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
          weight: 200

