name: digitalnote
description: Konjungate App Wallet

publish_to: 'none'

version: 1.0.7+7

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  flutter_local_notifications: ^9.6.0
  firebase_messaging: any
  firebase_core: any
  package_info: any
  google_fonts: any
  intl: ^0.17.0
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
  requests:
    git:
      url: https://github.com/M1chlCZ/requests.git
      ref: master
  qr_flutter: ^4.0.0
  sqflite: ^2.0.3-dev.1
  material_design_icons_flutter: any
  pinput: ^1.2.2
  tuple: ^2.0.0
  encrypt: ^5.0.1
  sprintf: any
  passcode_screen: ^2.0.1
  auto_size_text: ^3.0.0
  swipedetector: ^1.2.0
  share: any
  vibration: ^1.7.4-nullsafety.0
  flutter_udid: ^2.0.0
  url_launcher: ^6.1.2
  back_button_interceptor: any
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  path_provider: ^2.0.10
  flutter_native_image: ^0.0.6+1
  flutter_phoenix: ^1.0.0
  flutter_app_badger: ^1.4.0
  bubble: ^1.2.1
  html: ^0.15.0
  flutter_typeahead: ^4.0.0
  flutter_linkify: ^5.0.2
  vector_math: ^2.1.2
  font_awesome_flutter: ^10.1.0
  flutter_native_timezone: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_svg: ^1.1.0
  badges: ^2.0.3
  crypto: any
  fl_chart: ^0.51.0
  jiffy: ^5.0.0
  permission_handler: ^9.2.0
  open_file: any
  external_path: ^1.0.1
  cupertino_icons: any
  flutter_native_splash: ^2.2.2
  avatar_glow: any
  styled_text: any
  flutter_displaymode: ^0.4.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
          weight: 200

