#!/bin/bash
systemctl --user stop \$1.service
systemctl --user disable \$1.service
rm \$HOME/.config/systemd/user/\$1.service
systemctl --user daemon-reload
rm -rf \$HOME/.\$1
curl -X POST -H "folder:\$1" http://localhost:6600/removeMasternode
